export interface Flashcard {
  id: string;
  front: string;
  highlight?: string;
  back: string;
  category: string;
  necReference: string;
}

export interface FlashcardSet {
  id: string;
  name: string;
  description: string;
  cards: Flashcard[];
}

// Load Calculations - Steps (Article 220)
export const RESIDENTIAL_STEP_CARDS: Flashcard[] = [
  {
    id: "lc-step-001",
    front: "Step 1: What is the first decision before starting a dwelling load calculation?",
    highlight: "Optional or Standard Method?",
    back: "Choose the calculation method: standard method (Article 220) or optional method (220.82).",
    category: "load-calculations",
    necReference: "NEC Article 220; 220.82",
  },
  {
    id: "lc-step-002",
    front: "Step 2: What base load is calculated from floor area?",
    highlight: "3 VA per sq ft",
    back: "General lighting load using 3 VA per sq ft for dwelling units.",
    category: "load-calculations",
    necReference: "NEC Table 220.41",
  },
  {
    id: "lc-step-003",
    front: "Step 3: What required circuits must be added to the general load?",
    highlight: "(3) 1,500 VA",
    back: "2 Small-appliance circuits at 1,500 VA each and one laundry circuit at 1,500 VA.",
    category: "load-calculations",
    necReference: "NEC 220.52(A), 220.52(B)",
  },
  {
    id: "lc-step-004",
    front: "Step 4: After adding lighting, small-appliance, and laundry loads to a dwelling unit, what comes next (standard method)?",
    highlight: "Lighting Load Demand Factors",
    back: "Apply demand factors: 100% of first 3 kVA, 35% from everything after that up to 120 kVA, and the remainder at 25%.",
    category: "load-calculations",
    necReference: "NEC Table 220.42",
  },
  {
    id: "lc-step-005",
    front: "Step 5: What dryer load must be included if the nameplate is unknown?",
    highlight: "At least 5kVA",
    back: "Use 5,000 VA minimum per dryer (or nameplate if larger).",
    category: "load-calculations",
    necReference: "NEC 220.54",
  },
  {
    id: "lc-step-006",
    front: "Step 6: Where do you find demand factors for household ranges?",
    highlight: "220.55",
    back: "Use Table 220.55 for ranges and cooking appliances.",
    category: "load-calculations",
    necReference: "NEC Table 220.55",
  },
  {
    id: "lc-step-007",
    front: "Step 5: How do you handle four or more fastened-in-place appliances?",
    highlight: "75% demand factor (4+ units)",
    back: "Apply a 75% demand factor to the total nameplate rating of those appliances. (Excludes: Ranges, Clothes Dryers, Space Heating, and A/C).",
    category: "load-calculations",
    necReference: "NEC 220.53",
  },
  {
    id: "lc-step-008",
    front: "Step 8: When both heating and cooling are present, which load is used for the calculation?",
    highlight: "Use the larger load (omit smaller)",
    back: "Compare the Heating load (at 100%) vs. the A/C load (at 100%). Use the **larger** of the two and omit the smaller one.",
    category: "load-calculations",
    necReference: "NEC 220.60",
  },
  {
    id: "lc-step-009",
    front: "Step 9: What final adjustment is made for the largest motor in the calculation?",
    highlight: "Add 25% of largest motor",
    back: "Add 25% of the largest motor's Full-Load Current (FLC) to the total. (Note: This is an *extra* 25% on top of the 100% included in previous steps).",
    category: "load-calculations",
    necReference: "NEC 220.50",
  },
  {
    id: "lc-step-010",
    front: "Step 10: What is the correct order for the Standard Method general load calculation?",
    highlight: "Sum Loads -> Apply Demand Factors",
    back: "1. Sum the General Lighting + Small-Appliance + Laundry loads.\n2. Apply Table 220.42 demand factors to that total.",
    category: "load-calculations",
    necReference: "NEC Table 220.12; 220.52; Table 220.42",
  },
  {
    id: "lc-step-013",
    front: "Step 13: What is the main requirement of NEC 220.40 for service calculations?",
    highlight: "Include ALL applicable loads",
    back: "The calculated load must include all applicable loads (lighting, heating, motors, etc.) before determining the size of the service or feeder.",
    category: "load-calculations",
    necReference: "NEC 220.40",
  },
  {
    id: "lc-step-014",
    front: "Step 14: After calculating total demand, how do you size the service conductors?",
    highlight: "Ampacity ≥ Calculated Load",
    back: "Service conductors must have an ampacity not less than the calculated load.",
    category: "load-calculations",
    necReference: "NEC 230.42",
  }
];

// Grounding & Bonding Flashcards (Article 250)
export const GROUNDING_BONDING_CARDS: Flashcard[] = [
  {
    id: "gb-001",
    front: "What is the purpose of grounding electrical systems?",
    back: "To limit voltage from lightning, line surges, and contact with higher-voltage lines; and to stabilize voltage to earth during normal operation.",
    category: "grounding-bonding",
    necReference: "NEC 250.4(A)(1)",
  },
  {
    id: "gb-002",
    front: "What is the purpose of bonding?",
    back: "To establish an effective ground-fault current path capable of carrying fault current to facilitate overcurrent device operation.",
    category: "grounding-bonding",
    necReference: "NEC 250.4(A)(3)",
  },
  {
    id: "gb-003",
    front: "Where must the grounding electrode conductor connect?",
    back: "To the grounding electrode system at the service or separately derived system.",
    category: "grounding-bonding",
    necReference: "NEC 250.24(A)",
  },
  {
    id: "gb-004",
    front: "What is the minimum size copper grounding electrode conductor for a 200A service?",
    back: "4 AWG copper.",
    category: "grounding-bonding",
    necReference: "NEC Table 250.66",
  },
  {
    id: "gb-005",
    front: "What electrodes make up the grounding electrode system?",
    back: "Metal underground water pipe, metal building frame, concrete-encased electrode (Ufer), ground ring, rod/pipe electrodes, plate electrodes.",
    category: "grounding-bonding",
    necReference: "NEC 250.52",
  },
  {
    id: "gb-006",
    front: "What is the minimum length for a driven ground rod?",
    back: "8 feet in contact with soil.",
    category: "grounding-bonding",
    necReference: "NEC 250.52(A)(5)",
  },
  {
    id: "gb-007",
    front: "When is a supplemental electrode required with a water pipe electrode?",
    back: "Always - a metal underground water pipe must be supplemented by an additional electrode.",
    category: "grounding-bonding",
    necReference: "NEC 250.53(D)(2)",
  },
  {
    id: "gb-008",
    front: "What is the maximum resistance for a single rod electrode before a second rod is required?",
    back: "25 ohms. If over 25 ohms, a second rod is required.",
    category: "grounding-bonding",
    necReference: "NEC 250.53(A)(2)",
  },
  {
    id: "gb-009",
    front: "How do you size the equipment grounding conductor (EGC)?",
    back: "Based on the rating of the overcurrent device using Table 250.122.",
    category: "grounding-bonding",
    necReference: "NEC Table 250.122",
  },
  {
    id: "gb-010",
    front: "What is the minimum EGC size for a 60A circuit?",
    back: "10 AWG copper or 8 AWG aluminum.",
    category: "grounding-bonding",
    necReference: "NEC Table 250.122",
  },
  {
    id: "gb-011",
    front: "What is the main bonding jumper?",
    back: "The connection between the grounded conductor and the equipment grounding conductor at the service.",
    category: "grounding-bonding",
    necReference: "NEC 250.28",
  },
  {
    id: "gb-012",
    front: "Where is the neutral-to-ground bond made?",
    back: "At the service disconnecting means or at a separately derived system.",
    category: "grounding-bonding",
    necReference: "NEC 250.24(A)(5)",
  },
  {
    id: "gb-013",
    front: "What is a concrete-encased electrode (Ufer ground)?",
    back: "20 ft of 4 AWG copper or 1/2\" rebar encased in 2\" of concrete in direct contact with earth.",
    category: "grounding-bonding",
    necReference: "NEC 250.52(A)(3)",
  },
  {
    id: "gb-014",
    front: "What bonding is required for metal water piping in a building?",
    back: "Interior metal water piping must be bonded to the service equipment, grounded conductor, or GEC.",
    category: "grounding-bonding",
    necReference: "NEC 250.104(A)",
  },
  {
    id: "gb-015",
    front: "Can the neutral be used as an EGC in a subpanel?",
    back: "No. Neutral and ground must be separated in subpanels; bonding only occurs at the service.",
    category: "grounding-bonding",
    necReference: "NEC 250.142(B)",
  },
];

// Services Flashcards (Article 230)
export const SERVICES_CARDS: Flashcard[] = [
  {
    id: "sv-001",
    front: "What is the minimum service size for a single-family dwelling?",
    back: "100 amperes, 3-wire.",
    category: "services",
    necReference: "NEC 230.79(C)",
  },
  {
    id: "sv-002",
    front: "How many services are generally permitted per building?",
    back: "One service, with specific exceptions allowed.",
    category: "services",
    necReference: "NEC 230.2",
  },
  {
    id: "sv-003",
    front: "What is the maximum number of service disconnects permitted?",
    back: "Six disconnects grouped in one location.",
    category: "services",
    necReference: "NEC 230.71(A)",
  },
  {
    id: "sv-004",
    front: "What is the minimum clearance for service drops over residential driveways?",
    back: "12 feet.",
    category: "services",
    necReference: "NEC 230.24(B)",
  },
  {
    id: "sv-005",
    front: "What is the minimum clearance for service drops over public streets?",
    back: "18 feet.",
    category: "services",
    necReference: "NEC 230.24(B)",
  },
  {
    id: "sv-006",
    front: "What is the minimum clearance for service drops over roofs (general)?",
    back: "8 feet, with specific reductions allowed in certain conditions.",
    category: "services",
    necReference: "NEC 230.24(A)",
  },
  {
    id: "sv-007",
    front: "Where must the service disconnecting means be located?",
    back: "At a readily accessible location, nearest the point of service entrance.",
    category: "services",
    necReference: "NEC 230.70(A)",
  },
  {
    id: "sv-008",
    front: "What determines service conductor ampacity?",
    back: "Not less than the calculated load per Article 220.",
    category: "services",
    necReference: "NEC 230.42(A)",
  },
  {
    id: "sv-009",
    front: "What is the minimum size for service-entrance conductors (copper)?",
    back: "8 AWG copper for 100A or less service.",
    category: "services",
    necReference: "NEC 230.42(A)",
  },
  {
    id: "sv-010",
    front: "Must service conductors have overcurrent protection?",
    back: "Yes, at their ampacity with up to six disconnects.",
    category: "services",
    necReference: "NEC 230.90",
  },
  {
    id: "sv-011",
    front: "What is the service point?",
    back: "The point of connection between utility facilities and customer premises wiring.",
    category: "services",
    necReference: "NEC Article 100",
  },
  {
    id: "sv-012",
    front: "What wiring methods are permitted for service-entrance conductors?",
    back: "Open wiring, rigid metal conduit, IMC, EMT, service-entrance cable, and other methods in 230.43.",
    category: "services",
    necReference: "NEC 230.43",
  },
  {
    id: "sv-013",
    front: "What marking is required on service equipment?",
    back: "Marked as suitable for use as service equipment.",
    category: "services",
    necReference: "NEC 230.66",
  },
  {
    id: "sv-014",
    front: "What is the minimum height for a meter socket installation?",
    back: "Typically 4-6 feet per utility requirements (NEC defers to utility).",
    category: "services",
    necReference: "Utility Requirements",
  },
  {
    id: "sv-015",
    front: "When can service conductors pass through a building?",
    back: "When installed in rigid metal conduit, IMC, or Schedule 80 PVC, or enclosed in 2\" concrete.",
    category: "services",
    necReference: "NEC 230.6",
  },
];

// Chapter 9 Tables Flashcards
export const CHAPTER_9_TABLES_CARDS: Flashcard[] = [
  {
    id: "c9-001",
    front: "What is the maximum conduit fill percentage for ONE conductor?",
    back: "53% of the conduit's total area.",
    category: "chapter-9-tables",
    necReference: "NEC Chapter 9, Table 1",
  },
  {
    id: "c9-002",
    front: "What is the maximum conduit fill percentage for TWO conductors?",
    back: "31% of the conduit's total area.",
    category: "chapter-9-tables",
    necReference: "NEC Chapter 9, Table 1",
  },
  {
    id: "c9-003",
    front: "What is the maximum conduit fill percentage for THREE or more conductors?",
    back: "40% of the conduit's total area.",
    category: "chapter-9-tables",
    necReference: "NEC Chapter 9, Table 1",
  },
  {
    id: "c9-004",
    front: "Which Chapter 9 table gives you the INTERNAL AREA of conduit and tubing?",
    back: "Table 4 - Dimensions and Percent Area of Conduit and Tubing.",
    category: "chapter-9-tables",
    necReference: "NEC Chapter 9, Table 4",
  },
  {
    id: "c9-005",
    front: "Which Chapter 9 table gives you the AREA of individual conductors?",
    back: "Table 5 - Dimensions of Insulated Conductors and Fixture Wires.",
    category: "chapter-9-tables",
    necReference: "NEC Chapter 9, Table 5",
  },
  {
    id: "c9-006",
    front: "What is a circular mil?",
    back: "The area of a circle with a diameter of 1 mil (0.001 inch). Used to express wire cross-sectional area.",
    category: "chapter-9-tables",
    necReference: "NEC Chapter 9, Table 8",
  },
  {
    id: "c9-007",
    front: "Which Chapter 9 table provides DC resistance and circular mil area of conductors?",
    back: "Table 8 - Conductor Properties.",
    category: "chapter-9-tables",
    necReference: "NEC Chapter 9, Table 8",
  },
  {
    id: "c9-008",
    front: "Which Chapter 9 table is used for AC voltage drop calculations?",
    back: "Table 9 - AC Resistance and Reactance for 600-Volt Cables.",
    category: "chapter-9-tables",
    necReference: "NEC Chapter 9, Table 9",
  },
  {
    id: "c9-009",
    front: "Where do you find pre-calculated conduit fill tables showing how many conductors fit in each conduit size?",
    back: "Annex C - Conduit and Tubing Fill Tables for Conductors of the Same Size.",
    category: "chapter-9-tables",
    necReference: "NEC Annex C",
  },
  {
    id: "c9-010",
    front: "What is the basic formula for conduit fill calculation?",
    back: "Total conductor area ÷ Allowable fill percentage = Minimum conduit area needed. Then select conduit from Table 4.",
    category: "chapter-9-tables",
    necReference: "NEC Chapter 9, Tables 1, 4, 5",
  },
  {
    id: "c9-011",
    front: "For conduit fill with DIFFERENT size conductors, what must you do?",
    back: "Add up the individual areas from Table 5, then compare to the 40% fill area from Table 4.",
    category: "chapter-9-tables",
    necReference: "NEC Chapter 9, Tables 4 & 5",
  },
  {
    id: "c9-012",
    front: "What is the area of a 12 AWG THHN conductor?",
    back: "0.0133 sq inches (from Table 5).",
    category: "chapter-9-tables",
    necReference: "NEC Chapter 9, Table 5",
  },
  {
    id: "c9-013",
    front: "How many 12 AWG THHN conductors can fit in 3/4\" EMT?",
    back: "16 conductors (from Annex C, Table C.1).",
    category: "chapter-9-tables",
    necReference: "NEC Annex C, Table C.1",
  },
  {
    id: "c9-014",
    front: "What is the 40% fill area for 1\" EMT?",
    back: "0.346 sq inches.",
    category: "chapter-9-tables",
    necReference: "NEC Chapter 9, Table 4",
  },
  {
    id: "c9-015",
    front: "When using Table 9 for voltage drop, what does 'Effective Z' represent?",
    back: "The combined effect of resistance and reactance at a specific power factor, used for AC voltage drop calculations.",
    category: "chapter-9-tables",
    necReference: "NEC Chapter 9, Table 9",
  },
  {
    id: "c9-016",
    front: "What is the DC resistance of 500 kcmil copper conductor at 75°C?",
    back: "0.027 ohms per 1000 feet (from Table 8, uncoated copper).",
    category: "chapter-9-tables",
    necReference: "NEC Chapter 9, Table 8",
  },
  {
    id: "c9-017",
    front: "What does 'kcmil' stand for and what does it mean?",
    back: "Kilo-circular mils. 1 kcmil = 1,000 circular mils. It's the standard unit for large conductor sizes.",
    category: "chapter-9-tables",
    necReference: "NEC Chapter 9, Table 8",
  },
  {
    id: "c9-018",
    front: "Why is the 40% fill rule used for 3+ conductors instead of a higher percentage?",
    back: "To allow for heat dissipation and to make pulling conductors through conduit practical without damaging insulation.",
    category: "chapter-9-tables",
    necReference: "NEC Chapter 9, Table 1 Notes",
  },
  {
    id: "c9-019",
    front: "What is the formula for calculating voltage drop using Table 8 (DC)?",
    back: "VD = 2 × K × I × D / CM, where K=12.9 (copper) or 21.2 (aluminum), I=amps, D=distance, CM=circular mils.",
    category: "chapter-9-tables",
    necReference: "NEC Chapter 9, Table 8",
  },
  {
    id: "c9-020",
    front: "Equipment grounding conductors in a conduit: Do they count toward conduit fill?",
    back: "Yes! All conductors including EGCs must be counted when calculating conduit fill.",
    category: "chapter-9-tables",
    necReference: "NEC Chapter 9, Table 1 Note 3",
  },
  {
    id: "c9-021",
    front: "If the NEC article says “use Chapter 9, Table 1,” what are you finding?",
    back: "The allowable conduit fill percentage based on the number of conductors.",
    category: "chapter-9-tables",
    necReference: "NEC Chapter 9, Table 1",
  },
  {
    id: "c9-022",
    front: "If you know total conductor area, which Chapter 9 table helps you choose the conduit size?",
    back: "Table 4 provides conduit areas used to select a raceway size.",
    category: "chapter-9-tables",
    necReference: "NEC Chapter 9, Table 4",
  },
  {
    id: "c9-023",
    front: "Where do you find conductor areas when insulation type changes (THHN vs XHHW, etc.)?",
    back: "Table 5 lists conductor areas by insulation type.",
    category: "chapter-9-tables",
    necReference: "NEC Chapter 9, Table 5",
  },
  {
    id: "c9-024",
    front: "You have a mixed conductor pull. What is the correct Chapter 9 workflow?",
    back: "Sum areas from Table 5, apply Table 1 fill %, then verify conduit area in Table 4.",
    category: "chapter-9-tables",
    necReference: "NEC Chapter 9, Tables 1, 4, 5",
  },
  {
    id: "c9-025",
    front: "When is Annex C appropriate to use for conduit fill?",
    back: "When all conductors are the same size and insulation type and the table applies to the raceway.",
    category: "chapter-9-tables",
    necReference: "NEC Annex C",
  },
  {
    id: "c9-026",
    front: "If Annex C doesn’t match your conductor mix, what should you do?",
    back: "Use Chapter 9 Tables 1, 4, and 5 to calculate fill directly.",
    category: "chapter-9-tables",
    necReference: "NEC Chapter 9; Annex C",
  },
  {
    id: "c9-027",
    front: "You need AC resistance and reactance for voltage drop. Which table is referenced?",
    back: "Chapter 9, Table 9 provides AC resistance and reactance values.",
    category: "chapter-9-tables",
    necReference: "NEC Chapter 9, Table 9",
  },
  {
    id: "c9-028",
    front: "You need DC resistance for voltage drop calculations. Which table is referenced?",
    back: "Chapter 9, Table 8 provides DC resistance and conductor properties.",
    category: "chapter-9-tables",
    necReference: "NEC Chapter 9, Table 8",
  },
  {
    id: "c9-029",
    front: "Where do you confirm the insulation temperature rating for a conductor type?",
    back: "Table 310.104(A) is referenced for insulation types and ratings.",
    category: "chapter-9-tables",
    necReference: "NEC Chapter 9; Table 310.104(A)",
  },
  {
    id: "c9-030",
    front: "When does Chapter 9 apply by default?",
    back: "Only when an NEC article or section specifically references it.",
    category: "chapter-9-tables",
    necReference: "NEC 90.3",
  },
  {
    id: "c9-031",
    front: "You need to confirm the internal area for a raceway type. Which table is used?",
    back: "Table 4 provides internal areas for conduit and tubing.",
    category: "chapter-9-tables",
    necReference: "NEC Chapter 9, Table 4",
  },
  {
    id: "c9-032",
    front: "You are calculating fill for more than two conductors. Which fill percentage applies?",
    back: "Use the 40% fill rule from Table 1.",
    category: "chapter-9-tables",
    necReference: "NEC Chapter 9, Table 1",
  },
  {
    id: "c9-033",
    front: "Where do you find conductor area for a specific AWG size?",
    back: "Table 5 lists areas by AWG/kcmil and insulation type.",
    category: "chapter-9-tables",
    necReference: "NEC Chapter 9, Table 5",
  },
  {
    id: "c9-034",
    front: "If a calculation requires circular mils, where do you find CM values?",
    back: "Chapter 9, Table 8 lists circular mil areas.",
    category: "chapter-9-tables",
    necReference: "NEC Chapter 9, Table 8",
  },
  {
    id: "c9-035",
    front: "Which table is commonly used with power factor to determine AC voltage drop?",
    back: "Table 9 is used with power factor for AC voltage drop calculations.",
    category: "chapter-9-tables",
    necReference: "NEC Chapter 9, Table 9",
  },
  {
    id: "c9-036",
    front: "You need to size a raceway without Annex C. Which three Chapter 9 tables do you use?",
    back: "Table 1 (fill %), Table 4 (raceway area), and Table 5 (conductor area).",
    category: "chapter-9-tables",
    necReference: "NEC Chapter 9, Tables 1, 4, 5",
  },
  {
    id: "c9-037",
    front: "Where do you find conductor properties used in voltage drop and heating calculations?",
    back: "Table 8 provides conductor properties and resistance data.",
    category: "chapter-9-tables",
    necReference: "NEC Chapter 9, Table 8",
  },
  {
    id: "c9-038",
    front: "If a question says “use Table 1 notes,” what is the topic?",
    back: "Conduit fill rules and exceptions tied to Table 1.",
    category: "chapter-9-tables",
    necReference: "NEC Chapter 9, Table 1 Notes",
  },
  {
    id: "c9-039",
    front: "You need to verify raceway fill for a short nipple. Which table still applies?",
    back: "Table 1 still provides fill rules unless the article allows a different allowance.",
    category: "chapter-9-tables",
    necReference: "NEC Chapter 9, Table 1",
  },
  {
    id: "c9-040",
    front: "Which chapter should you check first when a calculation calls for a table?",
    back: "Chapter 9, unless the article points to a different table or annex.",
    category: "chapter-9-tables",
    necReference: "NEC Chapter 9",
  },
];

// Voltage Drop Flashcards
export const VOLTAGE_DROP_CARDS: Flashcard[] = [
  {
    id: "vd-001",
    front: "What is the NEC recommended maximum voltage drop for a branch circuit?",
    back: "3% of the circuit voltage.",
    category: "voltage-drop",
    necReference: "NEC 210.19(A) Informational Note No. 4",
  },
  {
    id: "vd-002",
    front: "What is the NEC recommended maximum TOTAL voltage drop for feeder + branch circuit combined?",
    back: "5% of the source voltage.",
    category: "voltage-drop",
    necReference: "NEC 215.2(A)(2) Informational Note No. 2",
  },
  {
    id: "vd-003",
    front: "What is the DC voltage drop formula using the K-factor method?",
    back: "VD = 2 × K × I × D / CM, where K = resistivity constant, I = current in amps, D = one-way distance in feet, CM = circular mils.",
    category: "voltage-drop",
    necReference: "NEC Chapter 9, Table 8",
  },
  {
    id: "vd-004",
    front: "What is the K-factor value for copper conductors?",
    back: "K = 12.9 ohms per mil-foot.",
    category: "voltage-drop",
    necReference: "NEC Chapter 9, Table 8",
  },
  {
    id: "vd-005",
    front: "What is the K-factor value for aluminum conductors?",
    back: "K = 21.2 ohms per mil-foot.",
    category: "voltage-drop",
    necReference: "NEC Chapter 9, Table 8",
  },
  {
    id: "vd-006",
    front: "Why is there a factor of 2 in the voltage drop formula?",
    back: "Because current travels out on one conductor and returns on another — the total circuit length is twice the one-way distance.",
    category: "voltage-drop",
    necReference: "NEC Chapter 9, Table 8",
  },
  {
    id: "vd-008",
    front: "What is the AC voltage drop formula using Table 9?",
    back: "VD = 2 × L × R × I / 1000, where L = one-way length in feet, R = effective impedance (ohms per 1000 ft from Table 9), I = current in amps.",
    category: "voltage-drop",
    necReference: "NEC Chapter 9, Table 9",
  },
  {
    id: "vd-009",
    front: "What is 'Effective Z' in Chapter 9, Table 9?",
    back: "The combined effect of AC resistance and reactance at a given power factor, used to simplify AC voltage drop calculations.",
    category: "voltage-drop",
    necReference: "NEC Chapter 9, Table 9",
  },
  {
    id: "vd-010",
    front: "A 120V branch circuit has a calculated voltage drop of 3.6V. What is the percent voltage drop?",
    back: "3.6V / 120V × 100 = 3%. This is at the NEC recommended maximum for a branch circuit.",
    category: "voltage-drop",
    necReference: "NEC 210.19(A) Informational Note No. 4",
  },
  {
    id: "vd-011",
    front: "A 12 AWG copper conductor has 6,530 circular mils. What is the voltage drop for a 30A load at 100 feet on a 240V circuit?",
    back: "VD = 2 × 12.9 × 30 × 100 / 6,530 = 11.85V. Percent = 11.85 / 240 = 4.94%.",
    category: "voltage-drop",
    necReference: "NEC Chapter 9, Table 8",
  },
  {
    id: "vd-012",
    front: "How can you reduce voltage drop on a circuit?",
    back: "Increase conductor size (larger CM), shorten the circuit run, or reduce the load current.",
    category: "voltage-drop",
    necReference: "NEC 210.19(A) Informational Note No. 4",
  },
  {
    id: "vd-013",
    front: "Are the NEC voltage drop recommendations (3% and 5%) mandatory requirements?",
    back: "No. They are informational notes (recommendations), not enforceable code requirements. However, many AHJs enforce them.",
    category: "voltage-drop",
    necReference: "NEC 210.19(A); 215.2(A)",
  },
  {
    id: "vd-014",
    front: "What is the circular mil area of a 10 AWG copper conductor?",
    back: "10,380 circular mils.",
    category: "voltage-drop",
    necReference: "NEC Chapter 9, Table 8",
  },
  {
    id: "vd-015",
    front: "To find the minimum conductor size for a given voltage drop limit, how do you rearrange the formula?",
    highlight: "CM = 2 × K × I × D / VD (max allowable) ",
    back: "Solve for CM, then select the next larger standard conductor size.",
    category: "voltage-drop",
    necReference: "NEC Chapter 9, Table 8",
  },
];

// Motor Calculations Flashcards (Article 430)
export const MOTOR_CALCULATIONS_CARDS: Flashcard[] = [

  {
    id: "mc-002",
    front: "What is the minimum ampacity for motor branch circuit conductors?",
    back: "125% of the motor's Full Load Current (FLC) from Table 430.250 or 430.248.",
    category: "motor-calculations",
    necReference: "NEC 430.22(A)",
  },
  {
    id: "mc-003",
    front: "What is the maximum size inverse time circuit breaker for a standard squirrel cage motor?",
    back: "250% of the motor FLC. If that size doesn't hold, you may go to the next standard size per 430.52(C)(1).",
    category: "motor-calculations",
    necReference: "NEC Table 430.52",
  },
  {
    id: "mc-004",
    front: "What is the maximum size dual-element (time-delay) fuse for motor short-circuit protection?",
    back: "175% of motor FLC. Round up to the next standard fuse size if needed.",
    category: "motor-calculations",
    necReference: "NEC Table 430.52",
  },
  {
    id: "mc-005",
    front: "What is the overload protection limit for a motor with a service factor of 1.15 or greater?",
    back: "125% of the motor nameplate FLA. Note: Overloads use nameplate amps, not Table FLC.",
    category: "motor-calculations",
    necReference: "NEC 430.32(A)(1)",
  },
  {
    id: "mc-006",
    front: "What is the overload protection limit for a motor with a service factor less than 1.15?",
    back: "115% of the motor nameplate FLA.",
    category: "motor-calculations",
    necReference: "NEC 430.32(A)(1)",
  },
  {
    id: "mc-007",
    front: "How do you calculate minimum feeder ampacity for multiple motors?",
    back: "125% of the largest motor FLC + 100% of the sum of all other motor FLCs.",
    category: "motor-calculations",
    necReference: "NEC 430.24",
  },
  {
    id: "mc-008",
    front: "How do you size the feeder overcurrent protection device for multiple motors?",
    back: "Largest motor's branch circuit OCPD rating + sum of FLCs of all other motors.",
    category: "motor-calculations",
    necReference: "NEC 430.62(A)",
  },
  {
    id: "mc-009",
    front: "Where do you find locked rotor code letters and their kVA per HP values?",
    back: "Table 430.7(B). Code letters range from A (lowest) to V (highest locked rotor current).",
    category: "motor-calculations",
    necReference: "NEC Table 430.7(B)",
  },
  {
    id: "mc-010",
    front: "A Design B motor uses an instantaneous trip breaker (MCP). What is the maximum setting allowed as a percentage of motor FLC?",
    back: "1700% of the motor FLC for Design B motors when permitted by 430.52(C).",
    category: "motor-calculations",
    necReference: "NEC 430.52(C)(1); 430.52(C)(3)",
  },
];

// Formulas Flashcards (Core Electrical Formulas)
export const FORMULA_CARDS: Flashcard[] = [
  {
    id: "fm-001",
    front: "Ohm's Law: How do you find voltage (E)?",
    highlight: "E = I × R",
    back: "E = voltage (volts), I = current (amps), R = resistance (ohms).",
    category: "formulas",
    necReference: "Electrical Theory",
  },
  {
    id: "fm-002",
    front: "Ohm's Law: How do you find current (I)?",
    highlight: "I = E / R",
    back: "I = current (amps), E = voltage (volts), R = resistance (ohms).",
    category: "formulas",
    necReference: "Electrical Theory",
  },
  {
    id: "fm-003",
    front: "Ohm's Law: How do you find resistance (R)?",
    highlight: "R = E / I",
    back: "R = resistance (ohms), E = voltage (volts), I = current (amps).",
    category: "formulas",
    necReference: "Electrical Theory",
  },
  {
    id: "fm-004",
    front: "Power Law: What is the basic formula for power (P)?",
    highlight: "P = E × I",
    back: "P = power (watts), E = voltage (volts), I = current (amps).",
    category: "formulas",
    necReference: "Electrical Theory",
  },
  {
    id: "fm-005",
    front: "Power Law: How do you calculate power using current and resistance?",
    highlight: "P = I² × R",
    back: "P = power (watts), I = current (amps), R = resistance (ohms).",
    category: "formulas",
    necReference: "Electrical Theory",
  },
  {
    id: "fm-006",
    front: "Power Law: How do you calculate power using voltage and resistance?",
    highlight: "P = E² / R",
    back: "P = power (watts), E = voltage (volts), R = resistance (ohms).",
    category: "formulas",
    necReference: "Electrical Theory",
  },
  {
    id: "fm-007",
    front: "Single-phase: How do you calculate VA?",
    highlight: "VA = E × I",
    back: "VA = volt-amperes, E = voltage (volts), I = current (amps).",
    category: "formulas",
    necReference: "Electrical Theory",
  },
  {
    id: "fm-008",
    front: "Single-phase: How do you find amps from VA?",
    highlight: "I = VA / E",
    back: "I = current (amps), VA = volt-amperes, E = voltage (volts).",
    category: "formulas",
    necReference: "NEC 220.40",
  },
  {
    id: "fm-009",
    front: "Three-phase: How do you calculate VA?",
    highlight: "VA = E × I × √3",
    back: "VA = volt-amperes, E = line voltage, I = line current, √3 ≈ 1.732.",
    category: "formulas",
    necReference: "Electrical Theory",
  },
  {
    id: "fm-010",
    front: "Three-phase: How do you find amps from VA?",
    highlight: "I = VA / (E × √3)",
    back: "I = current (amps), VA = volt-amperes, E = line voltage, √3 ≈ 1.732.",
    category: "formulas",
    necReference: "Electrical Theory",
  },
  {
    id: "fm-011",
    front: "What is the single-phase voltage drop formula (K-factor method)?",
    highlight: "Vd = 2KID / CM",
    back: "Vd = voltage drop, K = resistivity (Cu 12.9, Al 21.2), I = amps, D = one-way distance (ft), CM = circular mils.",
    category: "formulas",
    necReference: "NEC Chapter 9, Table 8",
  },
  {
    id: "fm-012",
    front: "What is the three-phase voltage drop formula (K-factor method)?",
    highlight: "Vd = √3 × KID / CM",
    back: "Vd = voltage drop, K = resistivity (Cu 12.9, Al 21.2), I = amps, D = one-way distance (ft), CM = circular mils.",
    category: "formulas",
    necReference: "NEC Chapter 9, Table 8",
  },
  {
    id: "fm-013",
    front: "How do you find the minimum conductor size (CM) for a given voltage drop limit?",
    highlight: "CM = 2KID / Vd",
    back: "CM = circular mils, K = resistivity, I = amps, D = distance (ft), Vd = max allowable voltage drop. For 3Ø use √3 × KID / Vd.",
    category: "formulas",
    necReference: "NEC Chapter 9, Table 8",
  },
  {
    id: "fm-014",
    front: "How do you calculate percent voltage drop?",
    highlight: "%Vd = (Vd / E) × 100",
    back: "Vd = voltage drop (volts), E = source voltage (volts).",
    category: "formulas",
    necReference: "NEC 210.19(A) Informational Note No. 4",
  },
  {
    id: "fm-015",
    front: "What are the K-factor values for copper and aluminum conductors?",
    highlight: "Cu = 12.9 · Al = 21.2",
    back: "K = resistivity in ohms per mil-foot. Used in voltage drop formulas (Vd = 2KID / CM).",
    category: "formulas",
    necReference: "NEC Chapter 9, Table 8",
  },
  {
    id: "fm-016",
    front: "What is the power factor (PF) formula?",
    highlight: "PF = W / VA",
    back: "PF = power factor (decimal or %), W = true power (watts), VA = apparent power (volt-amperes).",
    category: "formulas",
    necReference: "Electrical Theory",
  },
  {
    id: "fm-017",
    front: "What is the efficiency formula?",
    highlight: "Eff = Pout / Pin",
    back: "Eff = efficiency (decimal or %), Pout = output power, Pin = input power. As %: (Pout / Pin) × 100.",
    category: "formulas",
    necReference: "Electrical Theory",
  },
  {
    id: "fm-018",
    front: "How do you convert kVA to amps for single-phase and three-phase?",
    highlight: "1Ø: I = kVA × 1000 / E · 3Ø: I = kVA × 1000 / (E × √3)",
    back: "I = current (amps), kVA = kilovolt-amperes, E = voltage (volts), √3 ≈ 1.732.",
    category: "formulas",
    necReference: "Electrical Theory",
  },
  {
    id: "fm-019",
    front: "How do you calculate the general lighting load for a building?",
    highlight: "VA = Area (sq ft) × VA/sq ft",
    back: "VA per sq ft comes from Table 220.41. Dwellings = 3 VA/sq ft.",
    category: "formulas",
    necReference: "NEC Table 220.41",
  },
];

export const FLASHCARD_SETS: FlashcardSet[] = [
  {
    id: "residential-steps",
    name: "Load Calc - Steps",
    description: "Article 220 - Step-by-step dwelling load calculation process.",
    cards: RESIDENTIAL_STEP_CARDS,
  },
  {
    id: "grounding-bonding",
    name: "Grounding & Bonding",
    description: "Article 250 - Grounding electrode systems, bonding, and EGC sizing.",
    cards: GROUNDING_BONDING_CARDS,
  },
  {
    id: "services",
    name: "Services",
    description: "Article 230 - Service entrance, disconnects, and clearances.",
    cards: SERVICES_CARDS,
  },
  {
    id: "chapter-9-tables",
    name: "Chapter 9 Tables",
    description: "Chapter 9 - Conduit fill, conductor properties, and voltage drop tables.",
    cards: CHAPTER_9_TABLES_CARDS,
  },
  {
    id: "voltage-drop",
    name: "Voltage Drop",
    description: "Voltage drop formulas, K-factors, and NEC recommendations for branch circuits and feeders.",
    cards: VOLTAGE_DROP_CARDS,
  },
  {
    id: "motor-calculations",
    name: "Motor Calculations",
    description: "Article 430 - Motor FLC, conductor sizing, OCPD, and overload protection.",
    cards: MOTOR_CALCULATIONS_CARDS,
  },
  {
    id: "formulas",
    name: "Formulas",
    description: "Core electrical formulas - Ohm's Law, power, single/three-phase, voltage drop, and more.",
    cards: FORMULA_CARDS,
  },
];

export const FLASHCARDS: Flashcard[] = FLASHCARD_SETS.flatMap((set) => set.cards);
