/**
 * Reads app/globals.css and emits ../sparkypass-ui/src/tokens.ts.
 * Run from web repo root: `npx tsx scripts/export-design-tokens.ts`
 *
 * Scope: only color tokens (hex + rgba) and font names. Skips oklch (RN doesn't
 * support easily), gradients, shadows, and the shadcn semantic aliases — those
 * are web-only.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const WEB_ROOT = resolve(__dirname, "..");
const UI_ROOT = resolve(WEB_ROOT, "../sparkypass-ui");
const CSS_PATH = resolve(WEB_ROOT, "app/globals.css");
const JSON_OUT = resolve(UI_ROOT, "src/tokens.json");
const TS_OUT = resolve(UI_ROOT, "src/tokens.ts");

// Allowlist of token-family prefixes worth porting to mobile.
const BRAND_PREFIXES = [
  "amber",
  "purple",
  "emerald",
  "sparky-green",
  "xp-green",
  "streak-fire",
  "correct",
  "error-color",
  "error-light",
  "cream",
];

// Standalone tokens we want even though they don't share a brand prefix.
const STANDALONE_TOKENS = new Set([
  "text-primary",
  "text-secondary",
  "text-muted",
  "bg-base",
  "bg-surface",
  "bg-elevated",
  "bg-card",
  "border-subtle",
  "border-medium",
  "border-strong",
]);

const FONT_FAMILIES = {
  sans: "Nunito",
  display: "Outfit",
  body: "Nunito",
  mono: "SpaceMono",
} as const;

function extractRootBlock(css: string): string {
  const match = css.match(/:root\s*\{([\s\S]*?)\n\}/);
  if (!match) throw new Error("Could not find :root block in globals.css");
  return match[1];
}

function parseVars(block: string): Map<string, string> {
  const result = new Map<string, string>();
  const lineRe = /--([a-z0-9-]+)\s*:\s*([^;]+);/gi;
  let m: RegExpExecArray | null;
  while ((m = lineRe.exec(block)) !== null) {
    const name = m[1].trim();
    const value = m[2].trim();
    if (value.includes("oklch") || value.includes("linear-gradient")) continue;
    result.set(name, value);
  }
  return result;
}

function isWanted(name: string): boolean {
  if (STANDALONE_TOKENS.has(name)) return true;
  return BRAND_PREFIXES.some((p) => name === p || name.startsWith(`${p}-`));
}

function buildTokens(vars: Map<string, string>): Record<string, unknown> {
  const wanted = [...vars.entries()]
    .filter(([k]) => isWanted(k))
    .sort(([a], [b]) => a.localeCompare(b));
  const colors: Record<string, string> = {};
  for (const [name, value] of wanted) colors[name] = value;
  return {
    colors,
    fonts: FONT_FAMILIES,
    radius: "0.625rem",
  };
}

const TS_WRAPPER = `// AUTO-GENERATED by sparkypass/scripts/export-design-tokens.ts
// Do not edit by hand. Regenerate after globals.css changes.
import tokensData from "./tokens.json";

export const tokens = tokensData;
export type Tokens = typeof tokensData;
export type ColorToken = keyof typeof tokensData.colors;
`;

function main() {
  const css = readFileSync(CSS_PATH, "utf8");
  const rootBlock = extractRootBlock(css);
  const vars = parseVars(rootBlock);
  const data = buildTokens(vars);
  writeFileSync(JSON_OUT, JSON.stringify(data, null, 2) + "\n");
  writeFileSync(TS_OUT, TS_WRAPPER);
  const colorCount = Object.keys((data as { colors: Record<string, string> }).colors).length;
  console.log(`Wrote ${JSON_OUT}`);
  console.log(`Wrote ${TS_OUT}`);
  console.log(`  ${colorCount} colors (from ${vars.size} :root vars)`);
  console.log(`  ${Object.keys(FONT_FAMILIES).length} font families`);
}

main();
